[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "metal"
roots = [".git"]
scope = "source.metal"
injection-regex = "metal"
file-types = ["metal"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
grammar = "cpp"
auto-format = true
