[[language]]
name = "metal"
roots = []
scope = "source.metal"
injection-regex = "metal"
file-types = ["metal"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
grammar = "cpp"
auto-format = true
